#!/usr/bin/env bash

# get directory where this script lives
source_dir="$( cd "$( [[ -h "${BASH_SOURCE[0]}" ]] && dirname "$(readlink "${BASH_SOURCE[0]}")" || dirname "${BASH_SOURCE[0]}" )" && pwd )"

# source common defaults
source "${source_dir}/.defaults.sh"

# TODO add docker

section_profiles=( packages google-cloud-sdk terraform packer keybase pre-commit ssh-config ssh-keys util-linux tmux trash-cli kubeval vim alacritty alacritty-terminfo jsonnet jd neovim ble.sh fzf jsonnet-lint )
meta_profiles=( all home work local remote )

if [[ "$1" == "" || "$1" == "-h" || "$1" == "--help" || "$1" == "help" ]]; then
    printf "section profiles:\n"
    printf "    %s\n" "${section_profiles[@]}" | sort | column
    printf "meta profiles:\n"
    printf "    %s\n" "${meta_profiles[@]}" | sort | column
    exit 2
fi

set -ex

declare -A dir
dir[base]="${HOME}/.local"
dir[bin]="${dir[base]}/bin"
dir[opt]="${dir[base]}/opt"
dir[share]="${dir[base]}/share"
dir[man]="${dir[share]}/man"
dir[man1]="${dir[man]}/man1"
dir[xdg_data_home]="${XDG_DATA_HOME:-"${default[XDG_DATA_HOME]}"}"
dir[completions]="${dir[xdg_data_home]}/bash-completion/completions"

if [[ "${XDG_DATA_HOME}" == "${HOME}/.local/share" ]]; then
    if [[ "${XDG_OVERRIDE}" != "true" ]]; then
        echo "XDG_DATA_HOME is not set or is set to spec defaults"
        echo "configure bash or run again with \"XDG_OVERRIDE=true\" in front"
        exit 1
    fi
fi

for key in "${!dir[@]}"; do mkdir -p "${dir[${key}]}"; done

# if "--install-pkgs" or "-p" arguments are given, enable package manager
if [[ "$1" == "--install-pkgs" || "$1" == "-p" ]]; then
    if command -v apt-get &>/dev/null; then
        family="deb"
        pkg_mgr="sudo apt-get --ignore-missing"
    elif command -v dnf &>/dev/null; then
        family="rhel"
        pkg_mgr="sudo dnf"
    elif command -v yum &>/dev/null; then
        family="rhel"
        pkg_mgr="sudo yum"
    else
        echo "unknown linux family"
        exit 1
    fi
else
    pkg_mgr=":"
fi

# make temp directory
dir[temp]="$(mktemp -d)"
chmod ugo+rx "${dir[temp]}"
cd "${dir[temp]}"

for profile in $@; do
    case ${profile} in
        all | home | work | packages )
            # install packages
            echo "installing packages..."
            mkdir "packages" && cd "packages"
            case ${family} in
                deb) ${pkg_mgr} update ;;
                rhel) ${pkg_mgr} makecache ;;
            esac
            packages_common=( git vim curl wget python3 python3-pip unzip sysstat pkg-config htop bash-completion )
            packages_deb=( apt-file python3-venv )
            packages_rpm=()
            packages=( ${packages_common[@]} )
            case ${family} in
                deb) packages+=( ${packages_deb[@]} ) ;;
                rhel) packages+=( ${packages_rpm[@]} ) ;;
            esac
            ${pkg_mgr} install -y ${packages[@]}
            cd "${dir[temp]}"
            ;;&
        all | work | google-cloud-sdk )
            # install google-cloud-sdk
            section="google-cloud-sdk"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            curl -sLo "gcloud_install.sh" "https://sdk.cloud.google.com/"
            chmod u+x "gcloud_install.sh"
            ./gcloud_install.sh --disable-prompts --install-dir="${dir[opt]}"
            ${dir[opt]}/google-cloud-sdk/bin/gcloud -q components install alpha beta cloud_sql_proxy kubectl
            ln -sf "${dir[opt]}/google-cloud-sdk/bin/cloud_sql_proxy" "${dir[bin]}/cloud_sql_proxy"
            ln -sf "${dir[opt]}/google-cloud-sdk/bin/docker-credential-gcloud" "${dir[bin]}/docker-credential-gcloud"
            ln -sf "${dir[opt]}/google-cloud-sdk/bin/gcloud" "${dir[bin]}/gcloud"
            ln -sf "${dir[opt]}/google-cloud-sdk/bin/git-credential-gcloud.sh" "${dir[bin]}/git-credential-gcloud.sh"
            ln -sf "${dir[opt]}/google-cloud-sdk/bin/gsutil" "${dir[bin]}/gsutil"
            ln -sf "${dir[opt]}/google-cloud-sdk/bin/kubectl" "${dir[bin]}/kubectl"
            ln -sf "${dir[opt]}/google-cloud-sdk/completion.bash.inc" "${dir[completions]}/google-cloud-sdk"
            "${dir[bin]}/kubectl" completion bash >"${dir[completions]}/kubectl"
            cd "${dir[temp]}"
            ;;&
        all | work | terraform )
            # install terraform
            section="terraform"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            # put version to be referred to as naked name last
            versions=( "0.11.14" "0.12.30" "0.13.6" "0.14.8" "0.12.29" )
            for version in "${versions[@]}"; do
                curl -sO "https://releases.hashicorp.com/${section}/${version}/${section}_${version}_linux_amd64.zip"
                unzip *
                rm "${section}_${version}_linux_amd64.zip"
                mv ${section} "${dir[bin]}/${section}-${version}"
                ln -sf "${dir[bin]}/${section}-${version}" "${dir[bin]}/${section}-${version%.*}"
            done
            ln -sf "${dir[bin]}/${section}-${version}" "${dir[bin]}/${section}"
            cd "${dir[temp]}"
            ;;&
        all | home | work | packer )
            # install packer
            section="packer"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            # put version to be referred to as naked name last
            versions=( "1.5.5" )
            for version in "${versions[@]}"; do
                curl -sO "https://releases.hashicorp.com/${section}/${version}/${section}_${version}_linux_amd64.zip"
                unzip *
                rm "${section}_${version}_linux_amd64.zip"
                mv ${section} "${dir[bin]}/${section}-${version}"
            done
            ln -sf "${dir[bin]}/${section}-${version}" "${dir[bin]}/${section}"
            cd "${dir[temp]}"
            ;;&
        all | home | work | keybase )
            # install keybase
            echo "installing keybase..."
            mkdir "keybase" && cd "keybase"
            if ! command -v keybase &>/dev/null; then
                case ${family} in
                    deb) keybase_file="keybase_amd64.deb" ;;
                    rhel) keybase_file="keybase_amd64.rpm" ;;
                esac
                curl -sO "https://prerelease.keybase.io/${keybase_file}"
                chmod ugo+r "${keybase_file}"
                ${pkg_mgr} install -y "./${keybase_file}"
            fi
            run_keybase -g
            cd "${dir[temp]}"
            ;;&
        all | home | work | pre-commit )
            # install pre-commit
            echo "installing pre-commit..."
            mkdir "pre-commit" && cd "pre-commit"
            python3 -m pip install --user pre-commit
            cd "${dir[temp]}"
            ;;&
        all | home | work | ssh-config )
            # install basic ssh-config
            echo "installing basic ssh config..."
            mkdir "ssh-config" && cd "ssh-config"
            if [[ ! -d "${HOME}/.ssh" ]]; then
                mkdir -p "${HOME}/.ssh"
                chmod 700 "${HOME}/.ssh"
            fi
            if [[ ! -f "${HOME}/.ssh/config" ]]; then
                cat >"${HOME}/.ssh/config" << EOL
Host *
    CanonicalizeHostname yes
    PreferredAuthentications publickey
    ServerAliveInterval 60

Host github.com
    IdentityFile ~/.ssh/${HOSTNAME}-to-github
    User rux616
EOL
                chmod 644 "${HOME}/.ssh/config"
            fi
            cd "${dir[temp]}"
            ;;&
        all | home | work | ssh-keys )
            # create some basic ssh keys
            echo "creating basic ssh keys..."
            mkdir "ssh-keys" && cd "ssh-keys"
            names=( "${HOSTNAME}-to-github" )
            types=( "ed25519" )
            for ((i=0; i<${#names[@]}; i++)); do
                if [[ ! -f "${HOME}/.ssh/${names[$i]}" ]]; then
                    ssh-keygen -q -t ${types[$i]} -C "${USER}@${names[$i]}" -N "" -f "${HOME}/.ssh/${names[$i]}"
                fi
            done
            cd "${dir[temp]}"
            ;;&
        all | home | work | util-linux )
            # install the *full* util-linux, which some distros don't seem to have
            section="util-linux"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            prereqs_common=( autoconf bison libtool automake )
            prereqs_deb=( autopoint gettext libncurses-dev libpam0g-dev libcap-ng-dev )
            prereqs_rpm=( gettext-devel ncurses-devel pam-devel libcap-ng-devel )
            prereqs=( ${prereqs_common[@]} )
            case ${family} in
                deb) prereqs+=( ${prereqs_deb[@]} ) ;;
                rhel) prereqs+=( ${prereqs_rpm[@]} ) ;;
            esac
            ${pkg_mgr} install -y ${prereqs[@]}
            latest_tarball="$(curl -sN "https://api.github.com/repos/karelzak/util-linux/tags" | grep -Pom 1 '"tarball_url": "\K.*?(?=")')"
            curl -sLo "${section}.tar.gz" "${latest_tarball}" && \
                tar -xf "${section}.tar.gz" --strip 1 && \
                ./autogen.sh && \
                ./configure --prefix="${dir[base]}" && \
                make && \
                sudo make install && \
                sudo chown -R ${USER}:${USER} "${dir[base]}"
            cd "${dir[temp]}"
            ;;&
        all | home | work | tmux )
            # install tmux
            section="tmux"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            prereqs_common=( autoconf bison libtool automake )
            prereqs_deb=( autopoint gettext libncurses-dev libevent-dev )
            prereqs_rpm=( gettext-devel ncurses-devel libevent-devel )
            prereqs=( ${prereqs_common[@]} )
            case ${family} in
                deb) prereqs+=( ${prereqs_deb[@]} ) ;;
                rhel) prereqs+=( ${prereqs_rpm[@]} ) ;;
            esac
            ${pkg_mgr} install -y ${prereqs[@]}
            latest_tarball="$(curl -sN "https://api.github.com/repos/tmux/tmux/releases/latest" | grep -Pom 1 '"tarball_url": "\K.*?(?=")')"
            curl -sLo "${section}.tar.gz" "${latest_tarball}" && \
                tar -xf "${section}.tar.gz" --strip 1 && \
                ./autogen.sh && \
                ./configure --prefix="${dir[base]}" && \
                make && \
                make install
            cd "${dir[temp]}"
            ;;&
        alacritty )
            # install alacritty
            section="alacritty"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            curl -sSfo "rust_install.sh" "https://sh.rustup.rs"
            chmod u+x "rust_install.sh"
            export CARGO_HOME="${PWD}/rust/.cargo"
            export RUSTUP_HOME="${PWD}/rust/.rustup"
            ./rust_install.sh -q -y --no-modify-path --default-toolchain stable --profile minimal
            prereqs_common=( cmake python3 )
            prereqs_deb=( pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev )
            prereqs_rpm=( freetype-devel fontconfig-devel libxcb-devel )
            prereqs=( ${prereqs_common[@]} )
            case ${family} in
                deb) prereqs+=( ${prereqs_deb[@]} ) ;;
                rhel) prereqs+=( ${prereqs_rpm[@]} ) ;;
            esac
            ${pkg_mgr} install -y ${prereqs[@]}
            latest_tarball="$(curl -sN "https://api.github.com/repos/alacritty/alacritty/releases/latest" | grep -Pom 1 '"tarball_url": "\K.*?(?=")')"
            curl -sLo "${section}.tar.gz" "${latest_tarball}" && \
                tar -xf "${section}.tar.gz" --strip 1 && \
                "${PWD}/rust/.cargo/bin/cargo" build --release && \
                mv -f "target/release/${section}" "${dir[bin]}/${section}" && \
                mv -f "extra/alacritty.man" "${dir[man1]}/alacritty.1" && \
                mv -f "extra/completions/alacritty.bash" "${dir[completions]}/alacritty" && \
                tic -xe alacritty,alacritty-direct "extra/alacritty.info"
            cd "${dir[temp]}"
            ;;&
        alacritty-terminfo )
            # install alacritty terminfo only
            section="alacritty-terminfo"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            latest_tarball="$(curl -sN "https://api.github.com/repos/alacritty/alacritty/releases/latest" | grep -Pom 1 '"tarball_url": "\K.*?(?=")')"
            curl -sLo "${section}.tar.gz" "${latest_tarball}" && \
                tar -xf "${section}.tar.gz" --strip 1 && \
                tic -xe alacritty,alacritty-direct "extra/alacritty.info"
            cd "${dir[temp]}"
            ;;&
        all | home | work | remote | local | trash-cli )
            # install trash-cli
            section="trash-cli"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            latest_tarball="$(curl -sN "https://api.github.com/repos/andreafrancia/trash-cli/tags" | grep -Pom 1 '"tarball_url": "\K.*?(?=")')"
            curl -sLo "${section}.tar.gz" "${latest_tarball}" && \
                tar -xf "${section}.tar.gz" --strip 1 && \
                python3 setup.py install --user
            mkdir -p "${dir[xdg_data_home]}/Trash"
            cd "${dir[temp]}"
            ;;&
        all | work | remote | local | kubeval )
            # install kubeval
            section="kubeval"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            release_file="${section}-linux-amd64.tar.gz"
            latest_release="https://github.com/instrumenta/${section}/releases/latest/download/${release_file}"
            curl -sLO "${latest_release}" && \
                tar -xf "${release_file}" && \
                mv -f "${section}" "${dir[bin]}/${section}"
            cd "${dir[temp]}"
            ;;&
        all | home | work | remote | local | vim )
            # install vim
            section="vim"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            # TODO --BEGIN--
            # TODO check what the actual prereqs are
            # TODO for now, run after installing tmux and/or util-linux
            #prereqs_common=( autoconf bison libtool automake python3 python3-dev )
            #prereqs_deb=( autopoint gettext libncurses-dev libncurses5-dev libevent-dev )
            #prereqs_rpm=( gettext-devel ncurses-devel libevent-devel )
            #prereqs=( ${prereqs_common[@]} )
            #case ${family} in
            #    deb) prereqs+=( ${prereqs_deb[@]} ) ;;
            #    rhel) prereqs+=( ${prereqs_rpm[@]} ) ;;
            #esac
            #${pkg_mgr} install -y ${prereqs[@]}
            # TODO --END--
            latest_tarball="$(curl -sN "https://api.github.com/repos/vim/vim/tags" | grep -Pom 1 '"tarball_url": "\K.*?(?=")')"
            curl -sLo "${section}.tar.gz" "${latest_tarball}" && \
                tar -xf "${section}.tar.gz" --strip 1 && \
                ./configure \
                    --with-features=huge \
                    --enable-python3interp=yes \
                    --with-python3-config-dir=$(python3-config --configdir) \
                    --prefix="${dir[base]}" && \
                make && \
                make install
            cd "${dir[temp]}"
            ;;&
        all | home | work | jsonnet )
            # install jsonnet
            section="jsonnet"
            repo="google/jsonnet"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            prereqs_common=( make g++ )
            prereqs_deb=()
            prereqs_rpm=()
            prereqs=( ${prereqs_common[@]} )
            case ${family} in
                deb) prereqs+=( ${prereqs_deb[@]} ) ;;
                rhel) prereqs+=( ${prereqs_rpm[@]} ) ;;
            esac
            ${pkg_mgr} install -y ${prereqs[@]}
            latest_tarball="$(curl -sN "https://api.github.com/repos/${repo}/releases/latest" | grep -Pom 1 '"tarball_url": "\K.*?(?=")')"
            curl -sLo "${section}.tar.gz" "${latest_tarball}" && \
                tar -xf "${section}.tar.gz" --strip 1 && \
                make && \
                PREFIX=${dir[base]} make install
            cd "${dir[temp]}"
            ;;&
        all | home | work | jd )
            # install jd
            section="jd"
            repo="josephburnett/jd"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            [[ -z ${latest_go} ]] && latest_go=$(git ls-remote --tags https://github.com/golang/go refs/tags/go* | awk -F '/' '{print $NF}' | sort -V | tail -n 1)
            GOPATH="${PWD}"
            GOBIN="${GOPATH}/bin"
            curl -sLo "go.tar.gz" "https://dl.google.com/go/${latest_go}.linux-amd64.tar.gz" && \
                tar -xf "go.tar.gz" && \
                go/bin/go get -u "github.com/${repo}" && \
                mv -f "bin/${section}" "${dir[bin]}/${section}"
            cd "${dir[temp]}"
            ;;&
        all | home | work | remote | local | neovim )
            # install neovim
            section="neovim"
            repo="neovim/neovim"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            prereqs_common=( ninja-build autoconf libtool automake cmake unzip )
            prereqs_deb=( gettext libtool-bin g++ pkg-config )
            prereqs_rpm=( gcc gcc-c++ pkgconfig patch make )
            prereqs=( ${prereqs_common[@]} )
            case ${family} in
                deb) prereqs+=( ${prereqs_deb[@]} ) ;;
                rhel) prereqs+=( ${prereqs_rpm[@]} ) ;;
            esac
            ${pkg_mgr} install -y ${prereqs[@]}
            latest_tarball="$(curl -sN "https://api.github.com/repos/${repo}/releases/latest" | grep -Pom 1 '"tarball_url": "\K.*?(?=")')"
            curl -sLo "${section}.tar.gz" "${latest_tarball}" && \
                tar -xf "${section}.tar.gz" --strip 1 && \
                make \
                    CMAKE_BUILD_TYPE=Release \
                    CMAKE_INSTALL_PREFIX="${dir[base]}" \
                    install
            cd "${dir[temp]}"
            ;;&
        all | home | work | remote | local | ble.sh )
            # install blesh
            section="ble.sh"
            section_actual="blesh"
            repo="akinomyoga/ble.sh"
            echo "installing ${section}..."
            mkdir "${section_actual}" && cd "${section_actual}"
            prereqs_common=( git make gawk )
            prereqs_deb=()
            prereqs_rpm=()
            prereqs=( ${prereqs_common[@]} )
            case ${family} in
                deb) prereqs+=( ${prereqs_deb[@]} ) ;;
                rhel) prereqs+=( ${prereqs_rpm[@]} ) ;;
            esac
            ${pkg_mgr} install -y ${prereqs[@]}
            git clone --recursive https://github.com/${repo}.git ${PWD}
            make all && \
                make INSDIR="${dir[xdg_data_home]}/${section_actual}" install
            sed -i "s|${dir[temp]}/${section_actual}|release:master|" "${dir[xdg_data_home]}/${section_actual}/ble.sh"
            cd "${dir[temp]}"
            ;;&
        all | home | work | fzf )
            # install fzf
            section="fzf"
            repo="junegunn/fzf"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            [[ -z ${latest_go} ]] && latest_go=$(git ls-remote --tags "https://github.com/golang/go" refs/tags/go* | awk -F '/' '{print $NF}' | sort -V | tail -n 1)
            GOPATH="${PWD}"
            GOBIN="${GOPATH}/bin"
            curl -sLo "go.tar.gz" "https://dl.google.com/go/${latest_go}.linux-amd64.tar.gz" && \
                tar -xf "go.tar.gz" && \
                go/bin/go get -u "github.com/${repo}" && \
                cp -f "bin/${section}" "${dir[bin]}/${section}" && \
                rm -rf "${dir[xdg_data_home]}/fzf/fzf" && \
                mkdir -p "${dir[xdg_data_home]}/fzf" && \
                cp -a "src/github.com/${repo}" "${dir[xdg_data_home]}/fzf/fzf" && \
                mkdir -p "${dir[man1]}" && \
                cp -r "src/github.com/${repo}/man/man1" "${dir[man]}"
            cd "${dir[temp]}"
            ;;&
        all | home | work | jsonnet-lint )
            # install jsonnet-lint
            section="jsonnet-lint"
            repo="google/go-jsonnet/linter/jsonnet-lint"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            [[ -z ${latest_go} ]] && latest_go=$(git ls-remote --tags https://github.com/golang/go refs/tags/go* | awk -F '/' '{print $NF}' | sort -V | tail -n 1)
            GOPATH="${PWD}"
            GOBIN="${GOPATH}/bin"
            curl -sLo "go.tar.gz" "https://dl.google.com/go/${latest_go}.linux-amd64.tar.gz" && \
                tar -xf "go.tar.gz" && \
                go/bin/go get -u "github.com/${repo}" && \
                mv -f "bin/${section}" "${dir[bin]}/${section}"
            cd "${dir[temp]}"
            ;;&
        all | home | work | go )
            # install go
            section="go"
            echo "installing ${section}..."
            mkdir "${section}" && cd "${section}"
            [[ -z ${latest_go} ]] && latest_go=$(git ls-remote --tags https://github.com/golang/go refs/tags/go* | awk -F '/' '{print $NF}' | sort -V | tail -n 1)
            curl -sLo "go.tar.gz" "https://dl.google.com/go/${latest_go}.linux-amd64.tar.gz"
            tar -xf "go.tar.gz"
            mkdir -p "${dir[opt]}/golang"
            mv "go" "${dir[opt]}/golang/${latest_go}"
            ln -fs "${dir[opt]}/golang/${latest_go}/bin/go" "${dir[bin]}/go"
            ln -fs "${dir[opt]}/golang/${latest_go}/bin/gofmt" "${dir[bin]}/gofmt"
            cd "${dir[temp]}"
            ;;&
    esac
done

# cleanup
rm -rf "${dir[temp]}"
unset dir key family pkg_mgr packages_common packages_deb packages_rpm packages versions names types section section_actual prereqs_common prereqs_deb prereqs_rpm prereqs latest_tarball latest_version keybase_file CARGO_HOME RUSTUP_HOME repo latest_go
