#!/usr/bin/env bash

# Turn on extended globbing and programmable completion
shopt -s extglob progcomp

# Blacklisted completions, causing problems with our code.
#
_blacklist_glob='@(acroread.sh)'

# Glob for matching various backup files.
#
_backup_glob='@(#*#|*@(~|.@(bak|orig|rej|swp|dpkg*|rpm@(orig|new|save))))'

# source user completion directory definitions
completions_dir="${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions"
if [[ -d $completions_dir && -r $completions_dir && -x $completions_dir ]]; then
    for i in "$completions_dir"/*; do
        [[ ${i##*/} != @($_backup_glob|Makefile*|$_blacklist_glob) \
            && -f $i && -r $i ]] && . "$i"
    done
fi

unset _blacklist_glob _backup_glob completions_dir i
